import Foundation

extension StringKey {
    var ru: String {
        switch self {
        // Tab
        case .tabHome: return "Главная"
        case .tabExplore: return "Карта"
        case .tabFavorite: return "Избранное"
        case .tabBookings: return "Бронирования"
        case .tabProfile: return "Профиль"

        // Home
        case .homeGreeting: return "Привет"
        case .homeSubtitle: return "Найдите место для парковки"
        case .homeSearch: return "Поиск парковки..."
        case .homePopular: return "Популярные парковки"
        case .homeNearby: return "Поблизости"
        case .homeSeeAll: return "Все"
        case .homeNoParking: return "Парковка не найдена"
        case .homeNoResults: return "Ничего не найдено"
        case .homeCheckInternet: return "Проверьте интернет или настройки геолокации."
        case .homeLoadFailed: return "Не удалось загрузить парковки"
        case .homeRetry: return "Повторить"
        case .launchLoading: return "Загрузка данных..."
        case .launchFailed: return "Не удалось запустить приложение"
        case .retry: return "Повторить"

        // Explore
        case .exploreTitle: return "Карта"
        case .exploreSearch: return "Поиск адреса..."

        // Favorite
        case .favoriteTitle: return "Избранное"
        case .favoriteEmpty: return "Нет избранных"
        case .favoriteEmptySubtitle: return "Добавьте парковки в избранное."

        // Bookings
        case .bookingsTitle: return "Бронирования"
        case .bookingsActive: return "Активные"
        case .bookingsCompleted: return "Завершённые"
        case .bookingsCancelled: return "Отменённые"
        case .bookingsEmpty: return "Нет бронирований"
        case .bookingsEmptySubtitle: return "Вы ещё не бронировали."

        // Profile
        case .profileTitle: return "Профиль"
        case .profileAccount: return "Аккаунт"
        case .profileYourProfile: return "Ваш профиль"
        case .profilePaymentMethods: return "Способы оплаты"
        case .profileMyWallet: return "Кошелёк"
        case .profilePreferences: return "Настройки"
        case .profileSettings: return "Настройки"
        case .profileSupport: return "Поддержка"
        case .profileHelpCenter: return "Центр помощи"
        case .profilePrivacyPolicy: return "Политика конфиденциальности"
        case .profileInviteFriends: return "Пригласить друзей"
        case .profileLogout: return "Выйти"
        case .profileLogoutConfirm: return "Вы действительно хотите выйти?"
        case .profileComingSoon: return "Скоро будет доступно."

        // Profile extra
        case .profileEditProfile: return "Редактировать профиль"
        case .profileMyVehicles: return "Мои автомобили"
        case .profileNotifications: return "Уведомления"
        case .profileLanguage: return "Язык"
        case .profileDarkMode: return "Тёмный режим"
        case .profileTermsOfService: return "Условия использования"
        case .profileSignOut: return "Выйти"
        case .profileSignOutConfirm: return "Вы уверены, что хотите выйти?"
        case .profilePersonalInfo: return "Личная информация"
        case .profileUsername: return "Имя пользователя"
        case .profileEmail: return "Электронная почта"
        case .profilePhone: return "Телефон"
        case .profileSave: return "Сохранить"
        case .profileDone: return "Готово"
        case .profileNoVehicles: return "Транспортные средства не добавлены"
        case .profileAddPayment: return "Добавить способ оплаты"
        case .profileDefault: return "По умолчанию"
        case .profilePushNotifications: return "Push-уведомления"
        case .profileBookingAlerts: return "Уведомления о бронировании"
        case .profileTimeReminders: return "Напоминания о времени"
        case .profilePromotions: return "Акции и предложения"
        case .profileEmailSection: return "Email"
        case .profileEmailNotif: return "Email уведомления"
        case .profileVersion: return "Версия 1.0.0"
        case .profileUsernameEmpty: return "Имя пользователя не может быть пустым."
        case .profileSaveFailed: return "Не удалось сохранить профиль"
        case .profilePhotoUploadFailed: return "Не удалось загрузить фото. Попробуйте ещё раз."
        case .profilePaymentNotReady: return "Добавление способа оплаты пока недоступно."
        case .profileOnlyUsername:
            return "В настоящее время можно обновить только имя пользователя."

        // Settings
        case .settingsTitle: return "Настройки"
        case .settingsLanguage: return "Язык"
        case .settingsChooseLanguage: return "Выберите язык"
        case .settingsAppearance: return "Тема"
        case .settingsChooseTheme: return "Выберите тему"
        case .settingsColorTheme: return "Цветовая тема"
        case .themeCarbon: return "Карбон"
        case .themeOcean: return "Океан"
        case .themeForest: return "Лес"
        case .themeSunset: return "Закат"

        // Login
        case .loginTitle: return "Вход"
        case .loginSubtitle: return "Привет! С возвращением, мы скучали"
        case .loginEmail: return "Email"
        case .loginPassword: return "Пароль"
        case .loginEmailPlaceholder: return "example@gmail.com"
        case .loginPasswordPlaceholder: return "**********"
        case .loginForgotPassword: return "Забыли пароль?"
        case .loginSignIn: return "Войти"
        case .loginSigningIn: return "Вход..."
        case .loginNoAccount: return "Нет аккаунта?"
        case .loginSignUp: return "Регистрация"
        case .loginOrWith: return "Или войдите через"
        case .loginSocialDisabled: return "Вход через соцсети пока недоступен."
        case .loginErrorTitle: return "Ошибка входа"

        // Register
        case .registerTitle: return "Создать аккаунт"
        case .registerSubtitle: return "Заполните данные или зарегистрируйтесь через соцсети."
        case .registerName: return "Имя"
        case .registerNamePlaceholder: return "Например: Иван Иванов"
        case .registerAgreeWith: return "Согласен с"
        case .registerTerms: return "Условиями использования"
        case .registerSignUp: return "Регистрация"
        case .registerSigningUp: return "Регистрация..."
        case .registerHaveAccount: return "Уже есть аккаунт?"
        case .registerSignIn: return "Войти"
        case .registerErrorTitle: return "Ошибка регистрации"

        // Forgot
        case .forgotTitle: return "Сброс пароля"
        case .forgotSubtitle: return "Введите email, мы отправим код для сброса."
        case .forgotCodeTitle: return "Введите код"
        case .forgotCodeSubtitle: return "8-значный код отправлен на ваш email."
        case .forgotNewPassTitle: return "Новый пароль"
        case .forgotNewPassSubtitle: return "Введите и подтвердите новый пароль."
        case .forgotSendCode: return "Отправить код"
        case .forgotSending: return "Отправка..."
        case .forgotVerify: return "Подтвердить"
        case .forgotVerifying: return "Проверка..."
        case .forgotUpdatePassword: return "Обновить пароль"
        case .forgotSaving: return "Сохранение..."
        case .forgotResendIn: return "Отправить снова"
        case .forgotResendCode: return "Отправить код повторно"
        case .forgotConfirmCode: return "Код подтверждения"
        case .forgotNewPassword: return "Новый пароль"
        case .forgotConfirmPassword: return "Подтвердите пароль"
        case .forgotMinChars: return "Минимум 6 символов"
        case .forgotSuccessTitle: return "Успех!"
        case .forgotSuccessMessage: return "Пароль обновлён. Войдите с новым паролем."
        case .forgotGoToLogin: return "Перейти ко входу"
        case .forgotErrorTitle: return "Ошибка"

        // Validation
        case .valEmailRequired: return "Введите email"
        case .valEmailInvalid: return "Неверный формат email"
        case .valPasswordRequired: return "Введите пароль"
        case .valPasswordMin: return "Пароль должен быть не менее 6 символов"
        case .valNameRequired: return "Введите имя"
        case .valNameMin: return "Имя должно быть не менее 2 символов"
        case .valCodeRequired: return "Введите код"
        case .valCodeLength: return "Код состоит из 8 цифр"
        case .valConfirmRequired: return "Подтвердите пароль"
        case .valPasswordMismatch: return "Пароли не совпадают"

        // Strength
        case .strengthWeak: return "Слабый"
        case .strengthFair: return "Средний"
        case .strengthGood: return "Хороший"
        case .strengthStrong: return "Сильный"
        case .strengthVeryStrong: return "Очень сильный"

        // Parking Detail
        case .detailTotalSpots: return "всего мест"
        case .detailSpotsAvailable: return "мест свободно"
        case .detailDescription: return "Описание"
        case .detailNoDescription: return "Описание для этой парковки отсутствует."
        case .detailFeatures: return "Особенности"
        case .detailSecurity: return "Охрана 24/7"
        case .detailCCTV: return "Видеонаблюдение"
        case .detailLighting: return "Хорошее освещение"
        case .detailCovered: return "Крытая парковка"
        case .detailParkingInfo: return "О парковке"
        case .detailAvailable: return "Свободно"
        case .detailPrice: return "Цена"
        case .detailAdditionalInfo: return "Доп. информация"
        case .detailWorkingHours: return "Часы работы"
        case .detailPhone: return "Телефон"
        case .detailMaxHeight: return "Макс. высота"
        case .yesLabel: return "Да"
        case .noLabel: return "Нет"
        case .splashTagline: return "Найти • Забронировать • Парковать"
        case .detailTotalPrice: return "Общая цена"
        case .detailBookSlot: return "Забронировать"
        case .detailFullyBooked: return "Мест нет"
        case .detailAbout: return "О месте"
        case .detailGallery: return "Галерея"
        case .detailReview: return "Отзывы"
        case .detailNoGallery: return "Изображения галереи отсутствуют"
        case .detailReviews: return "Отзывы"
        case .detailAddReview: return "Добавить отзыв"
        case .detailBasedOnReviews: return "На основе отзывов"
        case .detailCarParking: return "Автопарковка"
        case .detailNavigate: return "Построить маршрут"
        case .detailNavigateWith: return "Открыть через"
        case .detailReviewEligibility: return "Оставить отзыв можно только по завершенному бронированию."
        case .detailReviewRating: return "Оценка"
        case .detailReviewComment: return "Комментарий"
        case .detailReviewCommentRequired: return "Пожалуйста, введите текст отзыва."
        case .detailSubmitReview: return "Отправить отзыв"
        case .detailNoReviewsYet: return "Пока нет отзывов"
        case .reviewNeedBookingWarning:
            return "Сначала забронируйте место на этой парковке, чтобы оставить отзыв."
        case .reviewAlreadySubmittedWarning:
            return "По вашим завершённым бронированиям отзывы уже отправлены."

        // Booking Flow
        case .bookingBookSlot: return "Забронировать"
        case .bookingReservationInfo:
            return "Бронирование начинается сейчас. Выберите продолжительность."
        case .bookingSelectDuration: return "Выберите время"
        case .bookingPrepaidAmount: return "Предоплата"
        case .bookingContinue: return "Продолжить"
        case .bookingProcessing: return "Обработка..."
        case .bookingMin: return "мин"
        case .bookingHour: return "час"
        case .bookingHours: return "часов"

        // Select Vehicle
        case .vehicleSelectTitle: return "Выбрать авто"
        case .vehicleNotFound: return "Авто не найдено"
        case .vehicleAddFirst: return "Сначала добавьте автомобиль."
        case .vehicleAddTitle: return "Добавить авто"
        case .vehicleSelectBrand: return "Выбрать марку"
        case .vehicleSelectCar: return "Выбрать авто"
        case .vehicleSelectModel: return "Выбрать модель"
        case .vehiclePlateNumber: return "Гос. номер"
        case .vehiclePlatePlaceholder: return "Напр. А 123 БВ"
        case .vehicleAdd: return "Добавить авто"
        case .vehicleDeleteTitle: return "Удалить автомобиль"
        case .vehicleDeleteConfirm: return "Вы хотите удалить этот автомобиль из списка?"
        case .vehicleDelete: return "Удалить"

        // Payment
        case .paymentTitle: return "Способы оплаты"
        case .paymentWallet: return "Кошелёк"
        case .paymentCreditDebit: return "Кредитная и дебетовая карта"
        case .paymentMoreOptions: return "Другие способы оплаты"
        case .paymentAddCard: return "Добавить карту"
        case .paymentConfirm: return "Подтвердить оплату"
        case .paymentSelectPayment: return "Выберите оплату"
        case .paymentChange: return "Изменить"
        case .paymentComingSoon: return "Этот способ оплаты появится в следующей версии."
        case .paymentWalletOnly: return "Сейчас поддерживается только оплата через кошелёк."

        // Review Summary
        case .reviewTitle: return "Итог бронирования"
        case .reviewArrivingTime: return "Время прибытия"
        case .reviewExitTime: return "Время выезда"
        case .reviewVehicle: return "Автомобиль"
        case .reviewDuration: return "Продолжительность"
        case .reviewAmount: return "Сумма"
        case .reviewTotalHours: return "Всего часов"
        case .reviewFees: return "Комиссия"
        case .reviewTotal: return "Итого"

        // Payment Success
        case .successPayment: return "Оплата"
        case .successTitle: return "Оплата успешна!"
        case .successMessage:
            return "Ваше место успешно забронировано.\nПроверьте бронирование в главном меню."
        case .successReservationId: return "Номер брони:"
        case .successViewReceipt: return "Посмотреть чек"
        case .successBackToHome: return "На главную"

        // E-Ticket / E-Receipt
        case .eticketTitle: return "Э-Билет"
        case .eticketClose: return "Закрыть"
        case .eticketStartTime: return "Время начала"
        case .eticketEndTime: return "Время окончания"
        case .eticketDuration: return "Продолжительность"
        case .eticketMinutes: return "мин"
        case .eticketActualEntry: return "Фактический въезд"
        case .eticketActualExit: return "Фактический выезд"
        case .eticketPricePerHour: return "Цена/час"
        case .eticketBaseAmount: return "Базовая сумма"
        case .eticketOvertimeCharge: return "Доп. оплата"
        case .eticketOvertime: return "Переработка!"
        case .eticketExtraCharge: return "Доп. оплата:"
        case .eticketTotal: return "Итого"
        case .receiptTitle: return "Эл. чек"
        case .receiptDownload: return "Скачать эл. чек"
        case .receiptCar: return "Автомобиль"
        case .receiptPlate: return "Гос. номер"
        case .receiptParking: return "Парковка"
        case .receiptAddress: return "Адрес"
        case .receiptRate: return "Тариф"
        case .receiptSubtotal: return "Подитог"
        case .receiptServiceFee: return "Сервисный сбор"
        case .receiptPaymentMethod: return "Способ оплаты"
        case .receiptDate: return "Дата"
        case .receiptStatus: return "Статус"
        case .receiptConfirmed: return "Подтверждено ✓"

        // Bookings View
        case .bookingsOngoing: return "Текущие"
        case .bookingsNoBookings: return "бронирований нет"
        case .bookingsAppearHere: return "бронирования появятся здесь"
        case .bookingsLoadFailed: return "Не удалось загрузить бронирования"
        case .bookingsCancelTitle: return "Отменить бронь"
        case .bookingsCancelConfirm: return "Вы уверены, что хотите отменить бронирование?"
        case .bookingsCancelYes: return "Да, отменить"
        case .bookingsCancelNo: return "Нет"
        case .bookingsTimer: return "Таймер"
        case .bookingsCancel: return "Отмена"
        case .bookingsView: return "Просмотр"
        case .bookingsETicket: return "Э-Билет"
        case .bookingsViewReceipt: return "Посмотреть чек"
        case .bookingsDetails: return "Подробности"
        case .bookingsStart: return "Начало"
        case .bookingsEnd: return "Конец"
        case .bookingsErrorCancel: return "Не удалось отменить:"

        // Bookings extra
        case .bookingsYesCancel: return "Да, отменить"
        case .bookingsNo: return "Нет"
        case .bookingsCancelMessage: return "Вы уверены, что хотите отменить эту бронь?"
        case .bookingsDuration: return "Продолжительность"
        case .bookingsActualEntry: return "Фактический въезд"
        case .bookingsActualExit: return "Фактический выезд"
        case .bookingsPricePerHour: return "Цена за час"
        case .bookingsBaseAmount: return "Основная сумма"
        case .bookingsOvertimeCharge: return "Плата за перестой"
        case .bookingsOvertime: return "Перестой!"
        case .bookingsExtraCharge: return "Дополнительная плата"
        case .bookingsRetry: return "Повторить"
        case .bookingsCannotCancel: return "Не удалось отменить"
        case .bookingsClose: return "Закрыть"
        case .bookingsPerHour: return "/час"
        case .bookingsUnknown: return "Неизвестно"

        // Status
        case .statusActive: return "Активный"
        case .statusInUse: return "Используется"
        case .statusCompleted: return "Завершено"
        case .statusCancelled: return "Отменено"
        case .statusExpired: return "Истекло"
        case .statusNoShow: return "Неявка"

        // Time ago
        case .timeNow: return "сейчас"
        case .timeMinAgo: return "мин"
        case .timeHourAgo: return "ч"
        case .timeDayAgo: return "д"

        // Notifications
        case .notifTitle: return "Уведомления"
        case .notifLoading: return "Загрузка уведомлений..."
        case .notifEmpty: return "Нет уведомлений"
        case .notifEmptySubtitle: return "Вы всё просмотрели!"
        case .notifToday: return "СЕГОДНЯ"
        case .notifYesterday: return "ВЧЕРА"
        case .notifOlder: return "РАНЕЕ"
        case .notifMarkAllRead: return "Прочитать все"
        case .notifNew: return "НОВОЕ"
        case .notifAllCaughtUp: return "Все уведомления прочитаны!"

        // Explore extra
        case .exploreNoResults: return "Ничего не найдено"
        case .exploreChangeSearch: return "Попробуйте другой запрос."
        case .exploreFilterInfo: return "Раздел фильтров появится в следующем обновлении."
        case .mapZoomIn: return "Увеличить"
        case .mapZoomOut: return "Уменьшить"

        // Home extra
        case .homeLocation: return "Местоположение"
        case .homeSearchParking: return "Поиск парковки"
        case .homePopularParking: return "Популярные парковки"
        case .homeNearbyParking: return "Парковки рядом"
        case .homeCityLabel: return "Город"
        case .homeSearchNoResults: return "Ничего не найдено"
        case .homeSearchNoResultsSub: return "Попробуйте другое название или адрес."

        // Favorite extra
        case .favoriteRemoveTitle: return "Удалить из избранного?"
        case .favoriteCancel: return "Отмена"
        case .favoriteYesRemove: return "Да, удалить"
        case .favoriteNoFavorites: return "Нет избранных"
        case .favoriteNoFavoritesSub: return "Ваши избранные парковки появятся здесь."

        // Wallet
        case .walletTitle: return "Кошелёк"
        case .walletBalance: return "Текущий баланс"
        case .walletTopUp: return "Пополнить"
        case .walletQuickTopUp: return "Быстрое пополнение"
        case .walletTransactions: return "Транзакции"
        case .walletNoTransactions: return "Нет транзакций"
        case .walletEnterAmount: return "Введите сумму"
        case .walletTopUpDone: return "Кошелёк пополнен"
        case .walletInsufficientBalance: return "Недостаточно средств"
        case .walletInvalidAmount: return "Неверная сумма"
        case .walletPaymentFor: return "Оплата парковки"
        case .walletCurrency: return "сум"

        // Common
        case .ok: return "ОК"
        case .cancel: return "Отмена"
        case .error: return "Ошибка"
        case .info: return "Информация"
        case .unknown: return "Неизвестно"
        case .back: return "Назад"

        // Admin - Editor
        case .adminSaving: return "Сохранение..."
        case .adminSave: return "Сохранить"
        case .adminEdit: return "Изменить парковку"
        case .adminNewParking: return "Новая парковка"
        case .adminAddParking: return "Добавить парковку"
        case .adminError: return "Ошибка"
        case .adminCancel: return "Отмена"
        case .adminBasicInfo: return "Основная информация"
        case .adminParkingName: return "Название парковки"
        case .adminSelectCity: return "Выберите город"
        case .adminAddress: return "Адрес"
        case .adminLocation: return "Местоположение"
        case .adminSearchLocation: return "Поиск адреса..."
        case .adminTapMapHint: return "Нажмите или удерживайте карту для точного местоположения"
        case .adminPriceCapacity: return "Цена и вместимость"
        case .adminPricePerHour: return "Цена за час (сум)"
        case .adminTotalSpots: return "Количество мест"
        case .adminDescription: return "Описание"
        case .adminFeatures: return "Удобства"
        case .adminImages: return "Фотографии"
        case .adminAddImage: return "Добавить фото"
        case .adminImageHint: return "Максимум 5 фото, формат JPEG, до 5 МБ каждое"
        case .adminDropHint: return "Перетащите фото или нажмите кнопку выше"

        // Admin - Dashboard
        case .adminDashboard: return "Панель управления"
        case .adminTotalParkings: return "Всего парковок"
        case .adminTotalRevenue: return "Общий доход"
        case .adminTotalReservations: return "Всего бронирований"
        case .adminActiveNow: return "Активных сейчас"
        case .adminQuickActions: return "Быстрые действия"
        case .adminViewReports: return "Отчёты"
        case .adminGreetingMorning: return "Доброе утро"
        case .adminGreetingDay: return "Добрый день"
        case .adminGreetingEvening: return "Добрый вечер"
        case .adminGreetingNight: return "Доброй ночи"

        // Admin - Parking List
        case .adminMyParkings: return "Мои парковки"
        case .adminSearchParkings: return "Поиск парковки..."
        case .adminEditParking: return "Изменить"
        case .adminDeleteParking: return "Удалить"
        case .adminDeleteConfirm: return "Вы уверены, что хотите удалить эту парковку?"
        case .adminDeleteYes: return "Да, удалить"
        case .adminDeleteNo: return "Отмена"
        case .adminNoParkings: return "Нет парковок"
        case .adminNoParkingsSub: return "Нажмите + чтобы добавить первую парковку"

        // Admin - Reservations
        case .adminReservations: return "Бронирования"
        case .adminAllParkings: return "Все"
        case .adminAllStatuses: return "Все статусы"
        case .adminNoReservations: return "Нет бронирований"
        case .adminFilterByParking: return "Фильтр по парковке"
        case .adminCancelReservation: return "Отменить бронирование"
        case .adminCancelReservationConfirm: return "Вы уверены, что хотите отменить это бронирование?"

        // Admin - Profile
        case .adminProfile: return "Профиль администратора"
        case .adminRealtimeConnected: return "Real-time подключён"
        case .adminRealtimeDisconnected: return "Real-time отключён"
        case .adminManageParkings: return "Управление парковками"
        case .adminStatsParkings: return "парковок"
        case .adminStatsReservations: return "бронирований"
        case .adminOwnerBadge: return "Владелец парковки"
        case .adminStatistics: return "Статистика"
        case .adminStatParkings: return "Парковки"
        case .adminStatCompleted: return "Завершённые"
        case .adminStatActive: return "Активные"
        case .adminLanguageLabel: return "Язык"
        case .adminAppearanceLabel: return "Вид"
        case .adminVersionLabel: return "Версия"
        case .adminClose: return "Закрыть"
        case .adminSelectLanguage: return "Выбор языка"
        case .adminSelectAppearance: return "Вид"
        case .adminSignOutTitle: return "Выйти"
        case .adminSignOutConfirm: return "Вы уверены, что хотите выйти?"
        }
    }
}
