import Foundation

extension StringKey {
    var uz: String {
        switch self {
        // Tab
        case .tabHome: return "Bosh sahifa"
        case .tabExplore: return "Xarita"
        case .tabFavorite: return "Sevimlilar"
        case .tabBookings: return "Buyurtmalar"
        case .tabProfile: return "Profil"

        // Home
        case .homeGreeting: return "Salom"
        case .homeSubtitle: return "Parking joyingizni toping"
        case .homeSearch: return "Parking qidirish..."
        case .homePopular: return "Ommabop parkinglar"
        case .homeNearby: return "Yaqin atrofdagi"
        case .homeSeeAll: return "Barchasi"
        case .homeNoParking: return "Parking topilmadi"
        case .homeNoResults: return "Natija topilmadi"
        case .homeCheckInternet: return "Internet yoki joylashuvni tekshirib ko'ring."
        case .homeLoadFailed: return "Parkinglar yuklanmadi"
        case .homeRetry: return "Qayta urinish"
        case .launchLoading: return "Ma'lumotlar yuklanmoqda..."
        case .launchFailed: return "Ilovani ishga tushirib bo'lmadi"
        case .retry: return "Qayta urinish"

        // Explore
        case .exploreTitle: return "Xarita"
        case .exploreSearch: return "Manzil qidirish..."

        // Favorite
        case .favoriteTitle: return "Sevimlilar"
        case .favoriteEmpty: return "Sevimlilar yo'q"
        case .favoriteEmptySubtitle: return "Parkinglarni sevimlilarga qo'shing."

        // Bookings
        case .bookingsTitle: return "Buyurtmalar"
        case .bookingsActive: return "Faol"
        case .bookingsCompleted: return "Tugallangan"
        case .bookingsCancelled: return "Bekor qilingan"
        case .bookingsEmpty: return "Buyurtmalar yo'q"
        case .bookingsEmptySubtitle: return "Hali birorta buyurtma bermadingiz."

        // Profile
        case .profileTitle: return "Profil"
        case .profileAccount: return "Hisob"
        case .profileYourProfile: return "Profilingiz"
        case .profilePaymentMethods: return "To'lov usullari"
        case .profileMyWallet: return "Hamyon"
        case .profilePreferences: return "Sozlamalar"
        case .profileSettings: return "Sozlamalar"
        case .profileSupport: return "Yordam"
        case .profileHelpCenter: return "Yordam markazi"
        case .profilePrivacyPolicy: return "Maxfiylik siyosati"
        case .profileInviteFriends: return "Do'stlarni taklif qilish"
        case .profileLogout: return "Chiqish"
        case .profileLogoutConfirm: return "Haqiqatan ham chiqmoqchimisiz?"
        case .profileComingSoon: return "Keyingi versiyada ochiladi."

        // Profile extra
        case .profileEditProfile: return "Profilni tahrirlash"
        case .profileMyVehicles: return "Transport vositalarim"
        case .profileNotifications: return "Bildirishnomalar"
        case .profileLanguage: return "Til"
        case .profileDarkMode: return "Qorong'u rejim"
        case .profileTermsOfService: return "Foydalanish shartlari"
        case .profileSignOut: return "Chiqish"
        case .profileSignOutConfirm: return "Haqiqatan ham chiqmoqchimisiz?"
        case .profilePersonalInfo: return "Shaxsiy ma'lumotlar"
        case .profileUsername: return "Foydalanuvchi nomi"
        case .profileEmail: return "Email"
        case .profilePhone: return "Telefon"
        case .profileSave: return "Saqlash"
        case .profileDone: return "Tayyor"
        case .profileNoVehicles: return "Transport vositalar qo'shilmagan"
        case .profileAddPayment: return "To'lov usulini qo'shish"
        case .profileDefault: return "Asosiy"
        case .profilePushNotifications: return "Push bildirishnomalar"
        case .profileBookingAlerts: return "Buyurtma ogohlantirishlari"
        case .profileTimeReminders: return "Vaqt eslatmalari"
        case .profilePromotions: return "Aksiya va takliflar"
        case .profileEmailSection: return "Email"
        case .profileEmailNotif: return "Email bildirishnomalar"
        case .profileVersion: return "Versiya 1.0.0"
        case .profileUsernameEmpty: return "Foydalanuvchi nomi bo'sh bo'lishi mumkin emas."
        case .profileSaveFailed: return "Profilni saqlab bo'lmadi"
        case .profilePhotoUploadFailed: return "Rasm yuklanmadi. Iltimos qayta urinib ko'ring."
        case .profilePaymentNotReady: return "To'lov usulini qo'shish hali mavjud emas."
        case .profileOnlyUsername: return "Hozircha faqat foydalanuvchi nomi yangilanadi."

        // Settings
        case .settingsTitle: return "Sozlamalar"
        case .settingsLanguage: return "Til"
        case .settingsChooseLanguage: return "Tilni tanlang"
        case .settingsAppearance: return "Mavzu"
        case .settingsChooseTheme: return "Mavzuni tanlang"
        case .settingsColorTheme: return "Rang mavzusi"
        case .themeCarbon: return "Carbon"
        case .themeOcean: return "Okean"
        case .themeForest: return "O'rmon"
        case .themeSunset: return "Quyosh botishi"

        // Login
        case .loginTitle: return "Kirish"
        case .loginSubtitle: return "Xush kelibsiz! Sizni sog'indik"
        case .loginEmail: return "Email"
        case .loginPassword: return "Parol"
        case .loginEmailPlaceholder: return "example@gmail.com"
        case .loginPasswordPlaceholder: return "**********"
        case .loginForgotPassword: return "Parolni unutdingizmi?"
        case .loginSignIn: return "Kirish"
        case .loginSigningIn: return "Kirilmoqda..."
        case .loginNoAccount: return "Hisobingiz yo'qmi?"
        case .loginSignUp: return "Ro'yxatdan o'tish"
        case .loginOrWith: return "Yoki quyidagilar bilan"
        case .loginSocialDisabled: return "Social kirish hozircha yoqilmagan."
        case .loginErrorTitle: return "Kirish xatosi"

        // Register
        case .registerTitle: return "Hisob yaratish"
        case .registerSubtitle:
            return "Ma'lumotlaringizni kiriting yoki ijtimoiy tarmoq orqali ro'yxatdan o'ting."
        case .registerName: return "Ism"
        case .registerNamePlaceholder: return "Masalan: Anvar Toshmatov"
        case .registerAgreeWith: return "Roziman"
        case .registerTerms: return "Foydalanish shartlari"
        case .registerSignUp: return "Ro'yxatdan o'tish"
        case .registerSigningUp: return "Ro'yxatdan o'tilmoqda..."
        case .registerHaveAccount: return "Hisobingiz bormi?"
        case .registerSignIn: return "Kirish"
        case .registerErrorTitle: return "Ro'yxatdan o'tish xatosi"

        // Forgot
        case .forgotTitle: return "Parolni tiklash"
        case .forgotSubtitle: return "Emailingizni kiriting, parolni tiklash uchun kod yuboramiz."
        case .forgotCodeTitle: return "Kodni kiriting"
        case .forgotCodeSubtitle: return "emailiga 8 xonali kod yuborildi."
        case .forgotNewPassTitle: return "Yangi parol"
        case .forgotNewPassSubtitle: return "Yangi parolni kiriting va tasdiqlang."
        case .forgotSendCode: return "Kod yuborish"
        case .forgotSending: return "Yuborilmoqda..."
        case .forgotVerify: return "Tasdiqlash"
        case .forgotVerifying: return "Tekshirilmoqda..."
        case .forgotUpdatePassword: return "Parolni yangilash"
        case .forgotSaving: return "Saqlanmoqda..."
        case .forgotResendIn: return "Qayta yuborish"
        case .forgotResendCode: return "Kodni qayta yuborish"
        case .forgotConfirmCode: return "Tasdiqlash kodi"
        case .forgotNewPassword: return "Yangi parol"
        case .forgotConfirmPassword: return "Parolni tasdiqlang"
        case .forgotMinChars: return "Kamida 6 ta belgi"
        case .forgotSuccessTitle: return "Muvaffaqiyat!"
        case .forgotSuccessMessage:
            return "Parolingiz muvaffaqiyatli yangilandi. Endi yangi parol bilan kiring."
        case .forgotGoToLogin: return "Kirish sahifasiga"
        case .forgotErrorTitle: return "Xatolik"

        // Validation
        case .valEmailRequired: return "Email kiritilishi shart"
        case .valEmailInvalid: return "Email formati noto'g'ri"
        case .valPasswordRequired: return "Parol kiritilishi shart"
        case .valPasswordMin: return "Parol kamida 6 ta belgi bo'lishi kerak"
        case .valNameRequired: return "Ism kiritilishi shart"
        case .valNameMin: return "Ism kamida 2 ta belgi bo'lishi kerak"
        case .valCodeRequired: return "Kodni kiriting"
        case .valCodeLength: return "Kod 8 ta raqamdan iborat"
        case .valConfirmRequired: return "Parolni tasdiqlang"
        case .valPasswordMismatch: return "Parollar mos kelmayapti"

        // Strength
        case .strengthWeak: return "Zaif"
        case .strengthFair: return "O'rtacha"
        case .strengthGood: return "Yaxshi"
        case .strengthStrong: return "Kuchli"
        case .strengthVeryStrong: return "Juda kuchli"

        // Parking Detail
        case .detailTotalSpots: return "jami joy"
        case .detailSpotsAvailable: return "joy mavjud"
        case .detailDescription: return "Tavsif"
        case .detailNoDescription: return "Bu parking haqida tavsif mavjud emas."
        case .detailFeatures: return "Xususiyatlar"
        case .detailSecurity: return "24/7 Qo'riqlash"
        case .detailCCTV: return "CCTV"
        case .detailLighting: return "Yaxshi yoritish"
        case .detailCovered: return "Yopiq parking"
        case .detailParkingInfo: return "Parking ma'lumotlari"
        case .detailAvailable: return "Mavjud"
        case .detailPrice: return "Narx"
        case .detailAdditionalInfo: return "Qo'shimcha ma'lumot"
        case .detailWorkingHours: return "Ish vaqti"
        case .detailPhone: return "Telefon"
        case .detailMaxHeight: return "Max balandlik"
        case .yesLabel: return "Ha"
        case .noLabel: return "Yo'q"
        case .splashTagline: return "Top • Band qil • Joylash"
        case .detailTotalPrice: return "Umumiy narx"
        case .detailBookSlot: return "Band qilish"
        case .detailFullyBooked: return "Joy yo'q"
        case .detailAbout: return "Haqida"
        case .detailGallery: return "Galereya"
        case .detailReview: return "Sharhlar"
        case .detailNoGallery: return "Galereya rasmlari mavjud emas"
        case .detailReviews: return "Sharhlar"
        case .detailAddReview: return "Sharh qo'shish"
        case .detailBasedOnReviews: return "Sharhlar asosida"
        case .detailCarParking: return "Avtoturargoh"
        case .detailNavigate: return "Yo'nalish olish"
        case .detailNavigateWith: return "Qaysi ilova orqali ochilsin?"
        case .detailReviewEligibility: return "Faqat yakunlangan buyurtma asosida sharh qoldira olasiz."
        case .detailReviewRating: return "Baholash"
        case .detailReviewComment: return "Fikr"
        case .detailReviewCommentRequired: return "Iltimos, sharh matnini kiriting."
        case .detailSubmitReview: return "Sharhni yuborish"
        case .detailNoReviewsYet: return "Hozircha sharhlar yo'q"
        case .reviewNeedBookingWarning: return "Avval shu parkingdan joy band qiling."
        case .reviewAlreadySubmittedWarning:
            return "Mavjud yakunlangan buyurtmalar bo'yicha sharh allaqachon qoldirilgan."

        // Booking Flow
        case .bookingBookSlot: return "Band qilish"
        case .bookingReservationInfo:
            return "Band qilish hozir boshlanadi. Qancha vaqt kerakligini tanlang."
        case .bookingSelectDuration: return "Vaqtni tanlang"
        case .bookingPrepaidAmount: return "Oldindan to'lov"
        case .bookingContinue: return "Davom etish"
        case .bookingProcessing: return "Jarayonda..."
        case .bookingMin: return "daq"
        case .bookingHour: return "soat"
        case .bookingHours: return "soat"

        // Select Vehicle
        case .vehicleSelectTitle: return "Mashina tanlash"
        case .vehicleNotFound: return "Mashina topilmadi"
        case .vehicleAddFirst: return "Davom etish uchun avval mashina qo'shing."
        case .vehicleAddTitle: return "Mashina qo'shish"
        case .vehicleSelectBrand: return "Brend tanlash"
        case .vehicleSelectCar: return "Mashina tanlash"
        case .vehicleSelectModel: return "Model tanlash"
        case .vehiclePlateNumber: return "Davlat raqami"
        case .vehiclePlatePlaceholder: return "Masalan: 01 A 123 AA"
        case .vehicleAdd: return "Mashina qo'shish"
        case .vehicleDeleteTitle: return "Mashinani o'chirish"
        case .vehicleDeleteConfirm: return "Ushbu mashinani ro'yxatdan olib tashlashni xohlaysizmi?"
        case .vehicleDelete: return "O'chirish"

        // Payment
        case .paymentTitle: return "To'lov usullari"
        case .paymentWallet: return "Hamyon"
        case .paymentCreditDebit: return "Kredit va debet karta"
        case .paymentMoreOptions: return "Boshqa to'lov usullari"
        case .paymentAddCard: return "Karta qo'shish"
        case .paymentConfirm: return "To'lovni tasdiqlash"
        case .paymentSelectPayment: return "To'lov usulini tanlang"
        case .paymentChange: return "O'zgartirish"
        case .paymentComingSoon: return "Bu to'lov usuli keyingi versiyalarda qo'shiladi."
        case .paymentWalletOnly: return "Hozircha faqat hamyon orqali to'lov qo'llab-quvvatlanadi."

        // Review Summary
        case .reviewTitle: return "Xulosa"
        case .reviewArrivingTime: return "Kelish vaqti"
        case .reviewExitTime: return "Chiqish vaqti"
        case .reviewVehicle: return "Mashina"
        case .reviewDuration: return "Davomiylik"
        case .reviewAmount: return "Narx"
        case .reviewTotalHours: return "Jami soat"
        case .reviewFees: return "Xizmat haqqi"
        case .reviewTotal: return "Jami"

        // Payment Success
        case .successPayment: return "To'lov"
        case .successTitle: return "To'lov muvaffaqiyatli!"
        case .successMessage:
            return "Parking joyingiz muvaffaqiyatli band qilindi.\nBuyurtmangizni bosh sahifada tekshirishingiz mumkin."
        case .successReservationId: return "Band raqami:"
        case .successViewReceipt: return "Elektron chekni ko'rish"
        case .successBackToHome: return "Bosh sahifaga"

        // E-Ticket / E-Receipt
        case .eticketTitle: return "E-Chipta"
        case .eticketClose: return "Yopish"
        case .eticketStartTime: return "Boshlanish vaqti"
        case .eticketEndTime: return "Tugash vaqti"
        case .eticketDuration: return "Davomiylik"
        case .eticketMinutes: return "daqiqa"
        case .eticketActualEntry: return "Haqiqiy kirish"
        case .eticketActualExit: return "Haqiqiy chiqish"
        case .eticketPricePerHour: return "Soatlik narx"
        case .eticketBaseAmount: return "Asosiy summa"
        case .eticketOvertimeCharge: return "Qo'shimcha to'lov"
        case .eticketOvertime: return "Vaqt o'tdi!"
        case .eticketExtraCharge: return "Qo'shimcha to'lov:"
        case .eticketTotal: return "Jami"
        case .receiptTitle: return "Elektron chek"
        case .receiptDownload: return "Elektron chekni yuklab olish"
        case .receiptCar: return "Mashina"
        case .receiptPlate: return "Davlat raqami"
        case .receiptParking: return "Parking"
        case .receiptAddress: return "Manzil"
        case .receiptRate: return "Tarif"
        case .receiptSubtotal: return "Oraliq summa"
        case .receiptServiceFee: return "Xizmat haqqi"
        case .receiptPaymentMethod: return "To'lov usuli"
        case .receiptDate: return "Sana"
        case .receiptStatus: return "Holat"
        case .receiptConfirmed: return "Tasdiqlangan ✓"

        // Bookings View
        case .bookingsOngoing: return "Faol"
        case .bookingsNoBookings: return "bandlar yo'q"
        case .bookingsAppearHere: return "bandlaringiz shu yerda ko'rinadi"
        case .bookingsLoadFailed: return "Bandlar yuklanmadi"
        case .bookingsCancelTitle: return "Bandni bekor qilish"
        case .bookingsCancelConfirm: return "Ushbu bandni bekor qilmoqchimisiz?"
        case .bookingsCancelYes: return "Ha, bekor qilish"
        case .bookingsCancelNo: return "Yo'q"
        case .bookingsTimer: return "Taymer"
        case .bookingsCancel: return "Bekor qilish"
        case .bookingsView: return "Ko'rish"
        case .bookingsETicket: return "E-Chipta"
        case .bookingsViewReceipt: return "Chekni ko'rish"
        case .bookingsDetails: return "Tafsilotlar"
        case .bookingsStart: return "Boshlanish"
        case .bookingsEnd: return "Tugash"
        case .bookingsErrorCancel: return "Bekor qilib bo'lmadi:"

        // Bookings extra
        case .bookingsYesCancel: return "Ha, bekor qilish"
        case .bookingsNo: return "Yo'q"
        case .bookingsCancelMessage: return "Bu buyurtmani bekor qilmoqchimisiz?"
        case .bookingsDuration: return "Davomiyligi"
        case .bookingsActualEntry: return "Haqiqiy kirish"
        case .bookingsActualExit: return "Haqiqiy chiqish"
        case .bookingsPricePerHour: return "Soatiga narx"
        case .bookingsBaseAmount: return "Asosiy summa"
        case .bookingsOvertimeCharge: return "Ortiqcha vaqt to'lovi"
        case .bookingsOvertime: return "Ortiqcha vaqt!"
        case .bookingsExtraCharge: return "Qo'shimcha to'lov"
        case .bookingsRetry: return "Qaytadan"
        case .bookingsCannotCancel: return "Bekor qilib bo'lmadi"
        case .bookingsClose: return "Yopish"
        case .bookingsPerHour: return "/soat"
        case .bookingsUnknown: return "Noma'lum"

        // Status
        case .statusActive: return "Faol"
        case .statusInUse: return "Foydalanilmoqda"
        case .statusCompleted: return "Tugallangan"
        case .statusCancelled: return "Bekor qilingan"
        case .statusExpired: return "Muddati o'tgan"
        case .statusNoShow: return "Kelmadi"

        // Time ago
        case .timeNow: return "hozir"
        case .timeMinAgo: return "daq"
        case .timeHourAgo: return "soat"
        case .timeDayAgo: return "kun"

        // Notifications
        case .notifTitle: return "Bildirishnomalar"
        case .notifLoading: return "Bildirishnomalar yuklanmoqda..."
        case .notifEmpty: return "Bildirishnomalar yo'q"
        case .notifEmptySubtitle: return "Hamma narsa ko'rib chiqilgan!"
        case .notifToday: return "BUGUN"
        case .notifYesterday: return "KECHA"
        case .notifOlder: return "OLDINGI"
        case .notifMarkAllRead: return "Hammasini o'qilgan deb belgilash"
        case .notifNew: return "YANGI"
        case .notifAllCaughtUp: return "Hamma bildirishnomalar o'qilgan!"

        // Explore extra
        case .exploreNoResults: return "Natija topilmadi"
        case .exploreChangeSearch: return "Qidiruv matnini o'zgartirib ko'ring."
        case .exploreFilterInfo: return "Filter bo'limi keyingi versiyada qo'shiladi."
        case .mapZoomIn: return "Yaqinlashtirish"
        case .mapZoomOut: return "Uzoqlashtirish"

        // Home extra
        case .homeLocation: return "Joylashuv"
        case .homeSearchParking: return "Parking qidirish"
        case .homePopularParking: return "Ommabop parkinglar"
        case .homeNearbyParking: return "Yaqin atrofdagi parkinglar"
        case .homeCityLabel: return "Shahar"
        case .homeSearchNoResults: return "Natija topilmadi"
        case .homeSearchNoResultsSub: return "Boshqa nom yoki manzil bilan qidirib ko'ring."

        // Favorite extra
        case .favoriteRemoveTitle: return "Sevimlilardan o'chirish?"
        case .favoriteCancel: return "Bekor qilish"
        case .favoriteYesRemove: return "Ha, o'chirish"
        case .favoriteNoFavorites: return "Sevimlilar yo'q"
        case .favoriteNoFavoritesSub: return "Yoqtirgan parkinglaringiz shu yerda chiqadi."

        // Wallet
        case .walletTitle: return "Hamyon"
        case .walletBalance: return "Joriy balans"
        case .walletTopUp: return "To'ldirish"
        case .walletQuickTopUp: return "Tez to'ldirish"
        case .walletTransactions: return "Tranzaksiyalar"
        case .walletNoTransactions: return "Tranzaksiyalar yo'q"
        case .walletEnterAmount: return "Ixtiyoriy summa kiriting"
        case .walletTopUpDone: return "Hamyon to'ldirildi"
        case .walletInsufficientBalance: return "Hamyonda mablag' yetarli emas"
        case .walletInvalidAmount: return "Noto'g'ri summa"
        case .walletPaymentFor: return "Parking to'lovi"
        case .walletCurrency: return "so'm"

        // Common
        case .ok: return "OK"
        case .cancel: return "Bekor qilish"
        case .error: return "Xatolik"
        case .info: return "Ma'lumot"
        case .unknown: return "Noma'lum"
        case .back: return "Orqaga"

        // Admin - Editor
        case .adminSaving: return "Saqlanmoqda..."
        case .adminSave: return "Saqlash"
        case .adminEdit: return "Tahrirlash"
        case .adminNewParking: return "Yangi parking"
        case .adminAddParking: return "Parking qo'shish"
        case .adminError: return "Xatolik"
        case .adminCancel: return "Bekor qilish"
        case .adminBasicInfo: return "Asosiy ma'lumotlar"
        case .adminParkingName: return "Parking nomi"
        case .adminSelectCity: return "Shaharni tanlang"
        case .adminAddress: return "Manzil"
        case .adminLocation: return "Joylashuv"
        case .adminSearchLocation: return "Manzil qidirish..."
        case .adminTapMapHint: return "Joylashuvni belgilash uchun xaritaga bosing yoki bosib turing"
        case .adminPriceCapacity: return "Narx va sig'im"
        case .adminPricePerHour: return "Soatlik narx (so'm)"
        case .adminTotalSpots: return "Joylar soni"
        case .adminDescription: return "Tavsif"
        case .adminFeatures: return "Qulayliklar"
        case .adminImages: return "Rasmlar"
        case .adminAddImage: return "Rasm qo'shish"
        case .adminImageHint: return "Maksimal 5 ta rasm, JPEG formatda, har biri 5 MB gacha"
        case .adminDropHint: return "Rasm tashlang yoki yuqoridagi tugmani bosing"

        // Admin - Dashboard
        case .adminDashboard: return "Boshqaruv paneli"
        case .adminTotalParkings: return "Jami parkinglar"
        case .adminTotalRevenue: return "Jami daromad"
        case .adminTotalReservations: return "Jami rezervatsiyalar"
        case .adminActiveNow: return "Hozir faol"
        case .adminQuickActions: return "Tezkor harakatlar"
        case .adminViewReports: return "Hisobotlar"
        case .adminGreetingMorning: return "Xayrli tong"
        case .adminGreetingDay: return "Xayrli kun"
        case .adminGreetingEvening: return "Xayrli kech"
        case .adminGreetingNight: return "Xayrli tun"

        // Admin - Parking List
        case .adminMyParkings: return "Parkinglarim"
        case .adminSearchParkings: return "Parking qidirish..."
        case .adminEditParking: return "Tahrirlash"
        case .adminDeleteParking: return "O'chirish"
        case .adminDeleteConfirm: return "Bu parkingni o'chirmoqchimisiz?"
        case .adminDeleteYes: return "Ha, o'chirish"
        case .adminDeleteNo: return "Bekor qilish"
        case .adminNoParkings: return "Parkinglar yo'q"
        case .adminNoParkingsSub: return "Yangi parking qo'shish uchun + tugmasini bosing"

        // Admin - Reservations
        case .adminReservations: return "Rezervatsiyalar"
        case .adminAllParkings: return "Barchasi"
        case .adminAllStatuses: return "Barcha holat"
        case .adminNoReservations: return "Rezervatsiyalar yo'q"
        case .adminFilterByParking: return "Parking bo'yicha filter"
        case .adminCancelReservation: return "Rezervatsiyani bekor qilish"
        case .adminCancelReservationConfirm: return "Ushbu rezervatsiyani bekor qilmoqchimisiz?"

        // Admin - Profile
        case .adminProfile: return "Admin profil"
        case .adminRealtimeConnected: return "Real-time ulanilgan"
        case .adminRealtimeDisconnected: return "Real-time uzilgan"
        case .adminManageParkings: return "Parkinglarni boshqarish"
        case .adminStatsParkings: return "ta parking"
        case .adminStatsReservations: return "ta rezervatsiya"
        case .adminOwnerBadge: return "Parking egasi"
        case .adminStatistics: return "Statistika"
        case .adminStatParkings: return "Parkinglar"
        case .adminStatCompleted: return "Tugallangan"
        case .adminStatActive: return "Faol"
        case .adminLanguageLabel: return "Til"
        case .adminAppearanceLabel: return "Ko'rinish"
        case .adminVersionLabel: return "Versiya"
        case .adminClose: return "Yopish"
        case .adminSelectLanguage: return "Til tanlash"
        case .adminSelectAppearance: return "Ko'rinish"
        case .adminSignOutTitle: return "Chiqish"
        case .adminSignOutConfirm: return "Hisobdan chiqishni tasdiqlaysizmi?"
        }
    }
}
