import Foundation

extension StringKey {
    var en: String {
        switch self {
        // Tab
        case .tabHome: return "Home"
        case .tabExplore: return "Explore"
        case .tabFavorite: return "Favorites"
        case .tabBookings: return "Bookings"
        case .tabProfile: return "Profile"

        // Home
        case .homeGreeting: return "Hello"
        case .homeSubtitle: return "Find your parking spot"
        case .homeSearch: return "Search parking..."
        case .homePopular: return "Popular parking"
        case .homeNearby: return "Nearby"
        case .homeSeeAll: return "See all"
        case .homeNoParking: return "No parking found"
        case .homeNoResults: return "No results found"
        case .homeCheckInternet: return "Check your internet or location settings."
        case .homeLoadFailed: return "Failed to load parking"
        case .homeRetry: return "Retry"
        case .launchLoading: return "Loading data..."
        case .launchFailed: return "Unable to launch app"
        case .retry: return "Retry"

        // Explore
        case .exploreTitle: return "Explore"
        case .exploreSearch: return "Search address..."

        // Favorite
        case .favoriteTitle: return "Favorites"
        case .favoriteEmpty: return "No favorites"
        case .favoriteEmptySubtitle: return "Add parking spots to your favorites."

        // Bookings
        case .bookingsTitle: return "Bookings"
        case .bookingsActive: return "Active"
        case .bookingsCompleted: return "Completed"
        case .bookingsCancelled: return "Cancelled"
        case .bookingsEmpty: return "No bookings"
        case .bookingsEmptySubtitle: return "You haven't made any bookings yet."

        // Profile
        case .profileTitle: return "Profile"
        case .profileAccount: return "Account"
        case .profileYourProfile: return "Your Profile"
        case .profilePaymentMethods: return "Payment Methods"
        case .profileMyWallet: return "My Wallet"
        case .profilePreferences: return "Preferences"
        case .profileSettings: return "Settings"
        case .profileSupport: return "Support"
        case .profileHelpCenter: return "Help Center"
        case .profilePrivacyPolicy: return "Privacy Policy"
        case .profileInviteFriends: return "Invite Friends"
        case .profileLogout: return "Log out"
        case .profileLogoutConfirm: return "Are you sure you want to log out?"
        case .profileComingSoon: return "Coming soon in the next update."

        // Profile extra
        case .profileEditProfile: return "Edit Profile"
        case .profileMyVehicles: return "My Vehicles"
        case .profileNotifications: return "Notifications"
        case .profileLanguage: return "Language"
        case .profileDarkMode: return "Dark Mode"
        case .profileTermsOfService: return "Terms of Service"
        case .profileSignOut: return "Sign Out"
        case .profileSignOutConfirm: return "Are you sure you want to sign out?"
        case .profilePersonalInfo: return "Personal Information"
        case .profileUsername: return "Username"
        case .profileEmail: return "Email"
        case .profilePhone: return "Phone"
        case .profileSave: return "Save"
        case .profileDone: return "Done"
        case .profileNoVehicles: return "No vehicles added"
        case .profileAddPayment: return "Add Payment Method"
        case .profileDefault: return "Default"
        case .profilePushNotifications: return "Push Notifications"
        case .profileBookingAlerts: return "Booking Alerts"
        case .profileTimeReminders: return "Time Reminders"
        case .profilePromotions: return "Promotions & Offers"
        case .profileEmailSection: return "Email"
        case .profileEmailNotif: return "Email Notifications"
        case .profileVersion: return "Version 1.0.0"
        case .profileUsernameEmpty: return "Username cannot be empty."
        case .profileSaveFailed: return "Failed to save profile"
        case .profilePhotoUploadFailed: return "Photo upload failed. Please try again."
        case .profilePaymentNotReady: return "Adding payment method is not yet available."
        case .profileOnlyUsername: return "Currently only the username can be updated."

        // Settings
        case .settingsTitle: return "Settings"
        case .settingsLanguage: return "Language"
        case .settingsChooseLanguage: return "Choose language"
        case .settingsAppearance: return "Appearance"
        case .settingsChooseTheme: return "Choose theme"
        case .settingsColorTheme: return "Color Theme"
        case .themeCarbon: return "Carbon"
        case .themeOcean: return "Ocean"
        case .themeForest: return "Forest"
        case .themeSunset: return "Sunset"

        // Login
        case .loginTitle: return "Sign In"
        case .loginSubtitle: return "Hi! Welcome back, you've been missed"
        case .loginEmail: return "Email"
        case .loginPassword: return "Password"
        case .loginEmailPlaceholder: return "example@gmail.com"
        case .loginPasswordPlaceholder: return "**********"
        case .loginForgotPassword: return "Forgot Password?"
        case .loginSignIn: return "Sign In"
        case .loginSigningIn: return "Signing In..."
        case .loginNoAccount: return "Don't have an account?"
        case .loginSignUp: return "Sign Up"
        case .loginOrWith: return "Or sign in with"
        case .loginSocialDisabled: return "Social sign in is not available yet."
        case .loginErrorTitle: return "Sign In Error"

        // Register
        case .registerTitle: return "Create Account"
        case .registerSubtitle:
            return "Fill your information below or register with your social account."
        case .registerName: return "Name"
        case .registerNamePlaceholder: return "Ex. John Doe"
        case .registerAgreeWith: return "Agree with"
        case .registerTerms: return "Terms & Conditions"
        case .registerSignUp: return "Sign Up"
        case .registerSigningUp: return "Signing Up..."
        case .registerHaveAccount: return "Already have an account?"
        case .registerSignIn: return "Sign In"
        case .registerErrorTitle: return "Sign Up Error"

        // Forgot
        case .forgotTitle: return "Reset Password"
        case .forgotSubtitle: return "Enter your email, we'll send you a reset code."
        case .forgotCodeTitle: return "Enter Code"
        case .forgotCodeSubtitle: return "An 8-digit code was sent to your email."
        case .forgotNewPassTitle: return "New Password"
        case .forgotNewPassSubtitle: return "Enter and confirm your new password."
        case .forgotSendCode: return "Send Code"
        case .forgotSending: return "Sending..."
        case .forgotVerify: return "Verify"
        case .forgotVerifying: return "Verifying..."
        case .forgotUpdatePassword: return "Update Password"
        case .forgotSaving: return "Saving..."
        case .forgotResendIn: return "Resend in"
        case .forgotResendCode: return "Resend Code"
        case .forgotConfirmCode: return "Verification Code"
        case .forgotNewPassword: return "New Password"
        case .forgotConfirmPassword: return "Confirm Password"
        case .forgotMinChars: return "At least 6 characters"
        case .forgotSuccessTitle: return "Success!"
        case .forgotSuccessMessage:
            return "Your password has been updated. Sign in with your new password."
        case .forgotGoToLogin: return "Go to Sign In"
        case .forgotErrorTitle: return "Error"

        // Validation
        case .valEmailRequired: return "Email is required"
        case .valEmailInvalid: return "Invalid email format"
        case .valPasswordRequired: return "Password is required"
        case .valPasswordMin: return "Password must be at least 6 characters"
        case .valNameRequired: return "Name is required"
        case .valNameMin: return "Name must be at least 2 characters"
        case .valCodeRequired: return "Enter the code"
        case .valCodeLength: return "Code must be 8 digits"
        case .valConfirmRequired: return "Please confirm your password"
        case .valPasswordMismatch: return "Passwords don't match"

        // Strength
        case .strengthWeak: return "Weak"
        case .strengthFair: return "Fair"
        case .strengthGood: return "Good"
        case .strengthStrong: return "Strong"
        case .strengthVeryStrong: return "Very Strong"

        // Parking Detail
        case .detailTotalSpots: return "total spots"
        case .detailSpotsAvailable: return "Spots Available"
        case .detailDescription: return "Description"
        case .detailNoDescription: return "No description available for this parking location."
        case .detailFeatures: return "Features"
        case .detailSecurity: return "24/7 Security"
        case .detailCCTV: return "CCTV"
        case .detailLighting: return "Good Lighting"
        case .detailCovered: return "Covered Parking"
        case .detailParkingInfo: return "Parking Info"
        case .detailAvailable: return "Available"
        case .detailPrice: return "Price"
        case .detailAdditionalInfo: return "Additional Info"
        case .detailWorkingHours: return "Hours"
        case .detailPhone: return "Phone"
        case .detailMaxHeight: return "Max Height"
        case .yesLabel: return "Yes"
        case .noLabel: return "No"
        case .splashTagline: return "Find • Book • Park"
        case .detailTotalPrice: return "Total Price"
        case .detailBookSlot: return "Book Slot"
        case .detailFullyBooked: return "Fully Booked"
        case .detailAbout: return "About"
        case .detailGallery: return "Gallery"
        case .detailReview: return "Review"
        case .detailNoGallery: return "No gallery images available"
        case .detailReviews: return "Reviews"
        case .detailAddReview: return "Add Review"
        case .detailBasedOnReviews: return "Based on reviews"
        case .detailCarParking: return "Car Parking"
        case .detailNavigate: return "Get Directions"
        case .detailNavigateWith: return "Open with"
        case .detailReviewEligibility: return "Only users with completed bookings can submit a review."
        case .detailReviewRating: return "Rating"
        case .detailReviewComment: return "Comment"
        case .detailReviewCommentRequired: return "Please enter your review comment."
        case .detailSubmitReview: return "Submit Review"
        case .detailNoReviewsYet: return "No reviews yet"
        case .reviewNeedBookingWarning: return "Book a slot at this parking first to leave a review."
        case .reviewAlreadySubmittedWarning:
            return "You already submitted reviews for your eligible bookings."

        // Booking Flow
        case .bookingBookSlot: return "Book Slot"
        case .bookingReservationInfo:
            return "Reservation starts now. Select how long you need the parking spot."
        case .bookingSelectDuration: return "Select duration"
        case .bookingPrepaidAmount: return "Prepaid amount"
        case .bookingContinue: return "Continue"
        case .bookingProcessing: return "Processing..."
        case .bookingMin: return "min"
        case .bookingHour: return "hour"
        case .bookingHours: return "hours"

        // Select Vehicle
        case .vehicleSelectTitle: return "Select Vehicle"
        case .vehicleNotFound: return "No vehicles found"
        case .vehicleAddFirst: return "Add a vehicle first to continue."
        case .vehicleAddTitle: return "Add Vehicle"
        case .vehicleSelectBrand: return "Select Brand"
        case .vehicleSelectCar: return "Select Car"
        case .vehicleSelectModel: return "Select model"
        case .vehiclePlateNumber: return "Car Number Plate"
        case .vehiclePlatePlaceholder: return "Ex. GR 789-IJKL"
        case .vehicleAdd: return "Add Vehicle"
        case .vehicleDeleteTitle: return "Delete Vehicle"
        case .vehicleDeleteConfirm: return "Are you sure you want to remove this vehicle?"
        case .vehicleDelete: return "Delete"

        // Payment
        case .paymentTitle: return "Payment Methods"
        case .paymentWallet: return "Wallet"
        case .paymentCreditDebit: return "Credit & Debit Card"
        case .paymentMoreOptions: return "More Payment Options"
        case .paymentAddCard: return "Add Card"
        case .paymentConfirm: return "Confirm Payment"
        case .paymentSelectPayment: return "Select Payment"
        case .paymentChange: return "Change"
        case .paymentComingSoon: return "This payment method will be available in the next version."
        case .paymentWalletOnly: return "Only wallet payment is supported for now."

        // Review Summary
        case .reviewTitle: return "Review Summary"
        case .reviewArrivingTime: return "Arriving Time"
        case .reviewExitTime: return "Exit Time"
        case .reviewVehicle: return "Vehicle"
        case .reviewDuration: return "Duration"
        case .reviewAmount: return "Amount"
        case .reviewTotalHours: return "Total Hours"
        case .reviewFees: return "Fees"
        case .reviewTotal: return "Total"

        // Payment Success
        case .successPayment: return "Payment"
        case .successTitle: return "Payment Successful!"
        case .successMessage:
            return "Your Parking Slot Successfully Booked.\nYou can check your booking on Home Menu."
        case .successReservationId: return "Reservation ID:"
        case .successViewReceipt: return "View E-Receipt"
        case .successBackToHome: return "Back to Home"

        // E-Ticket / E-Receipt
        case .eticketTitle: return "E-Ticket"
        case .eticketClose: return "Close"
        case .eticketStartTime: return "Start Time"
        case .eticketEndTime: return "End Time"
        case .eticketDuration: return "Duration"
        case .eticketMinutes: return "min"
        case .eticketActualEntry: return "Actual Entry"
        case .eticketActualExit: return "Actual Exit"
        case .eticketPricePerHour: return "Price/Hour"
        case .eticketBaseAmount: return "Base Amount"
        case .eticketOvertimeCharge: return "Overtime Charge"
        case .eticketOvertime: return "Overtime!"
        case .eticketExtraCharge: return "Extra Charge:"
        case .eticketTotal: return "Total"
        case .receiptTitle: return "E-Receipt"
        case .receiptDownload: return "Download E-Receipt"
        case .receiptCar: return "Car"
        case .receiptPlate: return "Car Number Plate"
        case .receiptParking: return "Parking"
        case .receiptAddress: return "Address"
        case .receiptRate: return "Rate"
        case .receiptSubtotal: return "Subtotal"
        case .receiptServiceFee: return "Service Fee"
        case .receiptPaymentMethod: return "Payment Method"
        case .receiptDate: return "Date"
        case .receiptStatus: return "Status"
        case .receiptConfirmed: return "Confirmed ✓"

        // Bookings View
        case .bookingsOngoing: return "Ongoing"
        case .bookingsNoBookings: return "Bookings"
        case .bookingsAppearHere: return "bookings will appear here"
        case .bookingsLoadFailed: return "Failed to load bookings"
        case .bookingsCancelTitle: return "Cancel Booking"
        case .bookingsCancelConfirm: return "Are you sure you want to cancel this booking?"
        case .bookingsCancelYes: return "Yes, Cancel"
        case .bookingsCancelNo: return "No"
        case .bookingsTimer: return "Timer"
        case .bookingsCancel: return "Cancel"
        case .bookingsView: return "View"
        case .bookingsETicket: return "E-Ticket"
        case .bookingsViewReceipt: return "View Receipt"
        case .bookingsDetails: return "Details"
        case .bookingsStart: return "Start"
        case .bookingsEnd: return "End"
        case .bookingsErrorCancel: return "Failed to cancel:"

        // Bookings extra
        case .bookingsYesCancel: return "Yes, Cancel"
        case .bookingsNo: return "No"
        case .bookingsCancelMessage: return "Are you sure you want to cancel this booking?"
        case .bookingsDuration: return "Duration"
        case .bookingsActualEntry: return "Actual Entry"
        case .bookingsActualExit: return "Actual Exit"
        case .bookingsPricePerHour: return "Price per Hour"
        case .bookingsBaseAmount: return "Base Amount"
        case .bookingsOvertimeCharge: return "Overtime Charge"
        case .bookingsOvertime: return "Overtime!"
        case .bookingsExtraCharge: return "Extra charge"
        case .bookingsRetry: return "Retry"
        case .bookingsCannotCancel: return "Cannot cancel"
        case .bookingsClose: return "Close"
        case .bookingsPerHour: return "/hr"
        case .bookingsUnknown: return "Unknown"

        // Status
        case .statusActive: return "Active"
        case .statusInUse: return "In Use"
        case .statusCompleted: return "Completed"
        case .statusCancelled: return "Cancelled"
        case .statusExpired: return "Expired"
        case .statusNoShow: return "No Show"

        // Time ago
        case .timeNow: return "now"
        case .timeMinAgo: return "m"
        case .timeHourAgo: return "h"
        case .timeDayAgo: return "d"

        // Notifications
        case .notifTitle: return "Notifications"
        case .notifLoading: return "Loading notifications..."
        case .notifEmpty: return "No Notifications"
        case .notifEmptySubtitle: return "You're all caught up!"
        case .notifToday: return "TODAY"
        case .notifYesterday: return "YESTERDAY"
        case .notifOlder: return "OLDER"
        case .notifMarkAllRead: return "Mark all read"
        case .notifNew: return "NEW"
        case .notifAllCaughtUp: return "You're all caught up!"

        // Explore extra
        case .exploreNoResults: return "No results found"
        case .exploreChangeSearch: return "Try a different search term."
        case .exploreFilterInfo: return "Filter section coming in next update."
        case .mapZoomIn: return "Zoom in"
        case .mapZoomOut: return "Zoom out"

        // Home extra
        case .homeLocation: return "Location"
        case .homeSearchParking: return "Search parking"
        case .homePopularParking: return "Popular parking"
        case .homeNearbyParking: return "Nearby parking"
        case .homeCityLabel: return "City"
        case .homeSearchNoResults: return "No results found"
        case .homeSearchNoResultsSub: return "Try searching with a different name or address."

        // Favorite extra
        case .favoriteRemoveTitle: return "Remove from favorites?"
        case .favoriteCancel: return "Cancel"
        case .favoriteYesRemove: return "Yes, Remove"
        case .favoriteNoFavorites: return "No Favorites"
        case .favoriteNoFavoritesSub: return "Your favorite parking spots will appear here."

        // Wallet
        case .walletTitle: return "Wallet"
        case .walletBalance: return "Current balance"
        case .walletTopUp: return "Top Up"
        case .walletQuickTopUp: return "Quick Top Up"
        case .walletTransactions: return "Transactions"
        case .walletNoTransactions: return "No transactions"
        case .walletEnterAmount: return "Enter custom amount"
        case .walletTopUpDone: return "Wallet topped up"
        case .walletInsufficientBalance: return "Insufficient balance"
        case .walletInvalidAmount: return "Invalid amount"
        case .walletPaymentFor: return "Parking payment"
        case .walletCurrency: return "so'm"

        // Common
        case .ok: return "OK"
        case .cancel: return "Cancel"
        case .error: return "Error"
        case .info: return "Info"
        case .unknown: return "Unknown"
        case .back: return "Back"

        // Admin - Editor
        case .adminSaving: return "Saving..."
        case .adminSave: return "Save"
        case .adminEdit: return "Edit Parking"
        case .adminNewParking: return "New Parking"
        case .adminAddParking: return "Add Parking"
        case .adminError: return "Error"
        case .adminCancel: return "Cancel"
        case .adminBasicInfo: return "Basic Information"
        case .adminParkingName: return "Parking name"
        case .adminSelectCity: return "Select city"
        case .adminAddress: return "Address"
        case .adminLocation: return "Location"
        case .adminSearchLocation: return "Search address..."
        case .adminTapMapHint: return "Tap or long-press on the map to set exact location"
        case .adminPriceCapacity: return "Price & Capacity"
        case .adminPricePerHour: return "Price per hour (so'm)"
        case .adminTotalSpots: return "Total spots"
        case .adminDescription: return "Description"
        case .adminFeatures: return "Features"
        case .adminImages: return "Images"
        case .adminAddImage: return "Add Images"
        case .adminImageHint: return "Max 5 images, JPEG format, up to 5 MB each"
        case .adminDropHint: return "Drop image here or tap the button above"

        // Admin - Dashboard
        case .adminDashboard: return "Dashboard"
        case .adminTotalParkings: return "Total Parkings"
        case .adminTotalRevenue: return "Total Revenue"
        case .adminTotalReservations: return "Total Reservations"
        case .adminActiveNow: return "Active Now"
        case .adminQuickActions: return "Quick Actions"
        case .adminViewReports: return "Reports"
        case .adminGreetingMorning: return "Good morning"
        case .adminGreetingDay: return "Good afternoon"
        case .adminGreetingEvening: return "Good evening"
        case .adminGreetingNight: return "Good night"

        // Admin - Parking List
        case .adminMyParkings: return "My Parkings"
        case .adminSearchParkings: return "Search parking..."
        case .adminEditParking: return "Edit"
        case .adminDeleteParking: return "Delete"
        case .adminDeleteConfirm: return "Are you sure you want to delete this parking?"
        case .adminDeleteYes: return "Yes, Delete"
        case .adminDeleteNo: return "Cancel"
        case .adminNoParkings: return "No parkings"
        case .adminNoParkingsSub: return "Tap + to add your first parking"

        // Admin - Reservations
        case .adminReservations: return "Reservations"
        case .adminAllParkings: return "All"
        case .adminAllStatuses: return "All statuses"
        case .adminNoReservations: return "No reservations"
        case .adminFilterByParking: return "Filter by parking"
        case .adminCancelReservation: return "Cancel Reservation"
        case .adminCancelReservationConfirm: return "Are you sure you want to cancel this reservation?"

        // Admin - Profile
        case .adminProfile: return "Admin Profile"
        case .adminRealtimeConnected: return "Real-time connected"
        case .adminRealtimeDisconnected: return "Real-time disconnected"
        case .adminManageParkings: return "Manage Parkings"
        case .adminStatsParkings: return "parkings"
        case .adminStatsReservations: return "reservations"
        case .adminOwnerBadge: return "Parking Owner"
        case .adminStatistics: return "Statistics"
        case .adminStatParkings: return "Parkings"
        case .adminStatCompleted: return "Completed"
        case .adminStatActive: return "Active"
        case .adminLanguageLabel: return "Language"
        case .adminAppearanceLabel: return "Appearance"
        case .adminVersionLabel: return "Version"
        case .adminClose: return "Close"
        case .adminSelectLanguage: return "Select Language"
        case .adminSelectAppearance: return "Appearance"
        case .adminSignOutTitle: return "Sign Out"
        case .adminSignOutConfirm: return "Are you sure you want to sign out?"
        }
    }
}
